# Generated by Django 3.2.6 on 2021-08-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forest',
            name='forest_img',
            field=models.ImageField(blank=True, null=True, upload_to='forest_img/', verbose_name='Forest Image'),
        ),
    ]
