# Generated by Django 3.2.6 on 2021-08-26 06:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0002_forest_forest_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forest',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
