# Generated by Django 3.2.6 on 2021-08-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nursery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_input', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('area_covered', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('species', models.TextField()),
                ('total_seedling', models.IntegerField()),
                ('description', models.TextField()),
                ('nursery_img', models.ImageField(blank=True, null=True, upload_to='nursery_img', verbose_name='Nursery Image')),
            ],
            options={
                'ordering': ['-date_input'],
            },
        ),
    ]
