# Generated by Django 3.2.6 on 2021-08-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_held', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('participant', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_img', models.ImageField(blank=True, null=True, upload_to='activity_img/', verbose_name='Activity image')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
