# Generated by Django 3.2.6 on 2021-08-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('PLANTING', 'Planting'), ('SEMINAR', 'Seminar'), ('WILDING', 'Wilding'), ('NURSERY', 'Nursery'), ('OFFICIAL', 'Official')], default='PLANTING', max_length=50),
        ),
        migrations.AddField(
            model_name='activity',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017')], default='2021', max_length=10),
        ),
    ]
