# Generated by Django 3.2.6 on 2021-08-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20210818_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('PLANTING', 'Planting'), ('CORPORATE', 'Corporate'), ('WILDING', 'Wilding'), ('NURSERY', 'Nursery')], default='PLANTING', max_length=50),
        ),
    ]
