# Generated by Django 3.2.6 on 2021-08-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='species_img',
            field=models.ImageField(blank=True, null=True, upload_to='species_img', verbose_name='Species Image'),
        ),
    ]
